# Generated by Django 5.0.1 on 2024-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.TextField(max_length=150),
        ),
    ]
