# Generated by Django 5.0.2 on 2024-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pfp',
            field=models.ImageField(default='images/avatar.svg', null=True, upload_to=''),
        ),
    ]
